name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
  
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Which device is this feature request for?
      options:
        - SF2000
        - GB300
        - Both
        - Other
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see added?
      placeholder: A clear description of the feature...
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be useful? What problem does it solve?
      placeholder: This would help with...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
    validations:
      required: false